### ISSUE TITLE
Generated CSS effects on other areas. Tried with ShadowDom but didn't work.

### ISSUE THREAD

**Issue by akib1997** [kolkov/angular-editor#489]
![image](https://user-images.githubusercontent.com/48770016/195598981-8ef9e39f-2d2a-4adf-ba6a-292c94d64e6b.png)

Generated CSS effects on other areas. Tried with ShadowDom but didn't work. Generated style tag overrides my CSS and effects them. I'm building a template Editor.

**Comment by Maransatto** [comment]
Hi @akib1997 
why did you close this issue?
I'm with the same issue.

I added the component into my own component with ViewEncapsulation.ShadowDom but now I'm facing the following error:

```
core.mjs:7635 ERROR TypeError: Cannot read properties of null (reading 'classList')
    at EmulatedEncapsulationDomRenderer2.removeClass (platform-browser.mjs:619:12)
    at BaseAnimationRenderer.removeClass (animations.mjs:280:23)
    at kolkov-angular-editor.mjs:642:24
    at Array.forEach (<anonymous>)
    at AngularEditorToolbarComponent.triggerButtons (kolkov-angular-editor.mjs:635:22)
    at AngularEditorComponent.exec (kolkov-angular-editor.mjs:1138:28)
    at AngularEditorComponent_Template_div_click_5_listener (kolkov-angular-editor.mjs:1203:2299)
    at executeListenerWithErrorHandling (core.mjs:15637:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15672:22)
    at HTMLDivElement.<anonymous> (platform-browser.mjs:459:38)
```

**Comment by tahsinpol** [comment]
+1
I have the same problem

`triggerButtons() {
        if (!this.showToolbar) {
            return;
        }
        this.buttons.forEach(e => {
            const result = this.doc.queryCommandState(e);
            const elementById = this.doc.getElementById(e + '-' + this.id);
            if (result) {
                this.r.addClass(elementById, 'active');
            }
            else {
                this.r.removeClass(elementById, 'active');
            }
        });
    }`

The object "this.doc" must be shadowRoot. Otherwise it cannot find it by doing getElementById from the parent document object

**Comment by matpinsdorf** [comment]
same problem here, with ViewEncapsulation.ShadowDom toolbar buttons lost sytle aswell ....


![image](https://github.com/kolkov/angular-editor/assets/57017667/2435a591-d6d3-4e69-9b96-27962133e354)
